version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
    
sphinx:
  fail_on_warning: true
  configuration: doc/source/conf.py


python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: layers/cibo
      extra_requirements:
        - docs
