# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "cibo-tilerlayer"

[default.build.parameters]
cached = true
parallel = true
build_image = "public.ecr.aws/sam/build-python3.12:latest-arm64"
use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = 'us-west-2'

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local.parameters]
skip_pull_image = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev]
[dev.global.parameters]
stack_name = "cibo-tilerlayer-dev"

[dev.build.parameters]
cached = true
parallel = true
build_image = "public.ecr.aws/sam/build-python3.12:latest-arm64"
use_container = true

[dev.deploy.parameters]
parameter_overrides = "Environment=\"dev\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-west-2"
s3_prefix = "cibo-tilerlayer-dev"
#disable_rollback = true
image_repositories = []
tags = ["LambdaDev=1"]

[dev.local_start_api.parameters]
parameter_overrides = "Environment=\"dev\""
warm_containers = "EAGER"
debug = true
log_file = "/dev/stdout"
region = 'us-west-2'

[dev.local_start_lambda.parameters]
parameter_overrides = "Environment=\"dev\""
warm_containers = "EAGER"
debug = true
log_file = "/dev/stdout"
region = 'us-west-2'

[prod]
[prod.global.parameters]
stack_name = "cibo-tilerlayer-prod"

[prod.build.parameters]
cached = true
parallel = true
build_image = "public.ecr.aws/sam/build-python3.12:latest-arm64"
use_container = true


[prod.deploy.parameters]
parameter_overrides = "Environment=\"prod\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "ap-southeast-2"
s3_prefix = "cibo-tilerlayer-prod"
#disable_rollback = true
image_repositories = []
tags = ["LambdaProd=1"]


[prod.local_start_api.parameters]
parameter_overrides = "Environment=\"prod\""
warm_containers = "EAGER"
debug = true
log_file = "/dev/stdout"
region = 'us-west-2'

[prod.local_start_lambda.parameters]
parameter_overrides = "Environment=\"prod\""
warm_containers = "EAGER"
debug = true
log_file = "/dev/stdout"
region = 'us-west-2'
